### ISSUE TITLE
Bulk price is not applying related sales.

### ISSUE THREAD

**Issue by webrained** [KuriousAgency/commerce-bulk-pricing#7]
Hi, I'm using bulk price plugin for my craft commerce website and it works for product variants, but when I append related sales to that variant bulk prices, plugin doesn't decrease the sale value.

**Comment by mcjackson18** [comment]
@webrained can you give an example of a sale you're trying to use - thanks.

**Comment by webrained** [comment]
I created new sale and assigned that sale to specific user groups.
Then I created and filled new bulk price for product variant and beyond the price supertable I filled related sales, with my created sale.
In twig template I can't get the discounted price.

**Comment by webrained** [comment]
![image (10)](https://user-images.githubusercontent.com/19373789/78667856-bf933f00-78ea-11ea-8da1-620b4a3db688.png)

**Comment by webrained** [comment]
See above, I have 3 prices for this variant and added related sales

**Comment by webrained** [comment]
![image (11)](https://user-images.githubusercontent.com/19373789/78667934-dc2f7700-78ea-11ea-9d71-e267ed84afb5.png)

This screenshot is showing the dump in twig template, so you can see it's returning just the base. prices, not discounted ones.

**Comment by webrained** [comment]
Is anyone here?

**Comment by webrained** [comment]
In your last commit I just can see something half baked, can you please elaborate about how's working the beyond:

https://github.com/KuriousAgency/commerce-bulk-pricing/blob/acc74756496cbac783fdab296ccec8c6960a8d7f/src/BulkPricing.php#L127

In both 127 and 128 row i can see that:
    $event->lineItem->salePrice = $value;
    $event->lineItem->price = $value;

In both cases it's assigning to $value.

And I need ability to show salePrice also before it's beginning to be lineItem, but also in product details page, so please let me know when can I expect those fixes.

Best regards
Arman T.

**Comment by mikeymeister** [comment]
Hi Arman, I hope you can accept our apologies for a slow response, our productivity has been affected by the current global coronavirus pandemic. 

The plugin currently is not compatible with commerce sales, the bulk price overrides any sales that apply. The previous commit resets the sale price to the reduced bulk price. This was required to fix issue #5 and an issue with another plugin. 

I have made some changes to allow sales to modify the bulk price in the development branch. Can you see if this fixes the problem you are seeing.

The plugin does not make changes to the purchasable until it becomes a lineItem because it requires the quantity value of the lineItem. Perhaps I am misunderstanding your final point?

**Comment by CMeldgaard** [comment]
@mikeymeister when will the changes regarding the sales you made in the develop branch make into production ?

**Comment by mcjackson18** [comment]
@CMeldgaard, the plugin has now been updated to support for Commerce Sales.

**Comment by mcjackson18** [comment]
@CMeldgaard, version 1.1.6 now supports Commerce Sales.

**Comment by terryupton** [comment]
Hey @mcjackson18 is there a way get the bulk discount sale price for showing this in a template?
Similar to the native `selectedVariant.salePrice` ?

Thanks
